/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ProjectLazyImport = createFileRoute('/project')()
const LogosLazyImport = createFileRoute('/logos')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ProjectLazyRoute = ProjectLazyImport.update({
  path: '/project',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/project.lazy').then((d) => d.Route))

const LogosLazyRoute = LogosLazyImport.update({
  path: '/logos',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/logos.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/logos': {
      id: '/logos'
      path: '/logos'
      fullPath: '/logos'
      preLoaderRoute: typeof LogosLazyImport
      parentRoute: typeof rootRoute
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  LogosLazyRoute,
  ProjectLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/logos",
        "/project"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/logos": {
      "filePath": "logos.lazy.tsx"
    },
    "/project": {
      "filePath": "project.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
