/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const WebdesignLazyImport = createFileRoute('/webdesign')()
const MoreLazyImport = createFileRoute('/more')()
const LogosLazyImport = createFileRoute('/logos')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const WebdesignLazyRoute = WebdesignLazyImport.update({
  path: '/webdesign',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/webdesign.lazy').then((d) => d.Route))

const MoreLazyRoute = MoreLazyImport.update({
  path: '/more',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/more.lazy').then((d) => d.Route))

const LogosLazyRoute = LogosLazyImport.update({
  path: '/logos',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/logos.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/logos': {
      id: '/logos'
      path: '/logos'
      fullPath: '/logos'
      preLoaderRoute: typeof LogosLazyImport
      parentRoute: typeof rootRoute
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreLazyImport
      parentRoute: typeof rootRoute
    }
    '/webdesign': {
      id: '/webdesign'
      path: '/webdesign'
      fullPath: '/webdesign'
      preLoaderRoute: typeof WebdesignLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  LogosLazyRoute,
  MoreLazyRoute,
  WebdesignLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/logos",
        "/more",
        "/webdesign"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/logos": {
      "filePath": "logos.lazy.tsx"
    },
    "/more": {
      "filePath": "more.lazy.tsx"
    },
    "/webdesign": {
      "filePath": "webdesign.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
